name: Node CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node_modules
        with:
          path: node_modules
          key: gas-cc-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            gas-cc-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
            gas-cc-build-${{ env.cache-name }}-
            gas-cc-build-

      - run: yarn install

      - run: yarn run lint
